### ISSUE TITLE
better way to parse parameters to CASA functions

### ISSUE THREAD

**Issue by jmoldon** [AMIGA-IAA/hcg_hi_pipeline#3]
Hi Mike,

I have seen this line in your recent commit:
https://github.com/AMIGA-IAA/hcg_hi_pipeline/blob/c6009c3f75923eb5be8250346a8373284106cf47/combine_clean_image.py#L33

and I would like to avoid a stroke on someone using/debugging/changing that in the future  :wink:. There are different ways to make it more readable and avoid future typos if you need to change something:

You can construct the string using **reference names instead of numbers**, that way it is very easy to make sure that the right parameter is used. Because most of your parameters are already in a dictionary, you can construct something like this:
```python
img_param = {'sourcename': 'XXX',
             'imsize':512,
             'niter':100}
command = "tclean(field='{sourcename}', imsize={imsize}, niter={niter})".format(**img_param)
```
```python

CASA <2>: command
Out[2]: "tclean(field='XXX', imsize=512, niter=100)"
```

You can also add new parameters or change the order in a more natural way, more similar to how CASA tasks are constructed. For example, if now you need to set the `gain` as a user parameter, it would be immediate.

You can also have a default dictionary for tclean with all those hard-coded values you have in that particular line and update only the ones that the user manually sets.

Just some ideas for when you are writing commands in the future, let me know if you need help.

**Comment by jmoldon** [comment]
Hi again,

I found a function I used some times to execute arbitrary functions with arbitrary parameter dictionaries, in case you want to use it:

```python
def run_casa_command(command, config_command):
    command_name = command.__name__
    logger.debug('Dictionary passed to {}'.format(command.__name__))
    logger.debug(config_command)
    logger.info('Running command: {}'.format(command_name))
    lines = []
    for (k,v) in config_command.iteritems():
        t = type(v)
        if t == str:
            lines.append('{0}="{1}"'.format(k,v))
        elif t == int or t == float:
            lines.append('{0}={1}'.format(k,v))
        elif t == list:
            lines.append('{0}="{1}"'.format(k,v))
        elif t == bool:
            lines.append('{0}={1}'.format(k,v))
        elif t == dict:
            lines.append('{0}={1}'.format(k,v))
        else:
            logger.warning('Could not identify type '
                           'of paremeter {0}, {1}'.format(k,v))
    output = '{0}({1})'.format(command.__name__, ', '.join(lines))
    logger.info(output)
    command(**config_command)
```

For the previous example you could use it with:
```python
run_casa_command(tclean, img_param)
```
The variable `command` is directly the CASA command, not its name, and `config_command` is the dictionary where the keys should be the same as the CASA task parameters. If you don't have a logger you can convert the logger calls to prints.

**Comment by jonesmg** [comment]
Hi Javi,

I implemented the tclean function in the combined imaging sctipt pulling the parameters from the dictionary by name as this is definitely less susceptible to typos. For the moment I'm not going to carry this backwards through all the other scripts though, as these are already more or less in a finished state. 

The function also looks very powerful, but as maybe half the parameters I use are basically fixed, by taking my approach where they are hard coded into the script it makes the parameters file a bit simpler, even though the code is perhaps less elegant.

Cheers,

Mike
